# Generated by Django 3.2.13 on 2022-05-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
