# Generated by Django 3.2.13 on 2022-05-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
