# Generated by Django 3.2.13 on 2022-05-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_password_uservault_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservault',
            old_name='user_password',
            new_name='password',
        ),
    ]
